name: Update PyTorch

on:
  schedule:
    - cron: "50 4 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'gh-pages'

      - name: Update Reports
        run: ./update-pytorch.sh

      - name: Commit Push
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "ci@github.io"
          git config --local user.name "Update CI"
          git add -A
          git commit -m "nightly update"
          git push
